# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

confDir = File.expand_path(File.dirname(__FILE__))

yamlFile = File.expand_path(File.dirname(__FILE__) + "/jammy.yaml")

require File.expand_path(File.dirname(__FILE__) + '/scripts/jammy.rb')

Vagrant.configure("2") do |config|
  if File.exist? yamlFile then
    settings = YAML::load(File.read(yamlFile))
  else
    abort ".yaml file not found in #{confDir}"
  end

  Jammy.configure(config, settings)
end
